import { writeFile } from 'node:fs/promises'
import { parse } from 'smol-toml'
import { z } from 'zod'
import { foldToJavaScript } from '#scan/case-fold'
import { translateToJavaScript } from '#scan/matcher'
import { GitleaksFetchError } from '#scripts/errors'

const SOURCE = 'https://raw.githubusercontent.com/gitleaks/gitleaks/master/config/gitleaks.toml'

/** Rules whose patterns fire on ordinary source code rather than on credentials.
 *  Each entry is a reason, not a preference. */
const DROPPED: ReadonlyMap<string, string> = new Map([
  ['generic-api-key', 'matches `key = <any 10+ chars>` — fires constantly on source code'],
  ['kubernetes-secret-yaml', 'keys on the bare word "secret" — fires on prose'],
])

const allowlistSchema = z.object({
  regexes: z.array(z.string()).catch([]),
})

const ruleSchema = z.object({
  id: z.string(),
  regex: z.string().nullable().catch(null),
  keywords: z.array(z.string()).catch([]),
  secretGroup: z.number().catch(0),
  entropy: z.number().catch(0),
  allowlists: z.array(allowlistSchema).catch([]),
})

const configSchema = z.object({ rules: z.array(ruleSchema) })

const adjusted: string[] = []

/**
 * Check a gitleaks pattern can run on the engine that will actually run it.
 *
 * Matching happens on JavaScript's regex engine, so that is what must accept
 * these patterns — either directly, or after `foldToJavaScript` rewrites Go's
 * scoped case-insensitivity into explicitly case-tolerant classes. A pattern
 * neither route accepts is dropped here with a reason rather than shipped as a
 * rule that silently never fires.
 *
 * Patterns themselves are emitted verbatim. The translation happens at load
 * time, so what ships is what gitleaks wrote.
 */
function checkTranslatable(id: string, pattern: string): string | null {
  if (translateToJavaScript(pattern) !== null) return null
  if (foldToJavaScript(pattern) !== null) {
    adjusted.push(`${id}: scoped case-insensitivity folded at load time`)
    return null
  }
  return `${id}: no JavaScript translation preserves what it matches`
}

const response = await fetch(SOURCE)
if (!response.ok) throw new GitleaksFetchError(response.status)

const config = configSchema.parse(parse(await response.text()))

const kept: string[] = []
const skipped: string[] = []

for (const rule of config.rules) {
  const reason = DROPPED.get(rule.id)
  if (reason) {
    skipped.push(`${rule.id}: ${reason}`)
    continue
  }
  if (rule.regex === null) {
    skipped.push(`${rule.id}: path-only rule, nothing to match against text`)
    continue
  }
  if (rule.keywords.length === 0) {
    skipped.push(`${rule.id}: no keywords, so the prefilter cannot reach it`)
    continue
  }

  // Checked here rather than at runtime: a rule that cannot run must fail the
  // build, not disappear silently from a shipped rule set.
  const pattern = rule.regex
  const allowlist = rule.allowlists.flatMap((entry) => entry.regexes)

  const untranslatable = [pattern, ...allowlist]
    .map((entry) => checkTranslatable(rule.id, entry))
    .find((reason) => reason !== null)

  if (untranslatable !== undefined && untranslatable !== null) {
    skipped.push(untranslatable)
    continue
  }

  kept.push(`  {
    id: ${JSON.stringify(rule.id)},
    keywords: [${rule.keywords.map((k) => JSON.stringify(k.toLowerCase())).join(', ')}],
    pattern: ${JSON.stringify(pattern)},
    group: ${rule.secretGroup},
    entropy: ${rule.entropy},
    allowlist: [${allowlist.map((entry) => JSON.stringify(entry)).join(', ')}],
  },`)
}

const file = `// GENERATED by scripts/generate-secret-rules.ts — do not edit.
// Source: ${SOURCE}
// gitleaks is MIT-licensed; these are its rule definitions, used verbatim.
//
// ${kept.length} rules kept, ${skipped.length} dropped:
${skipped.map((line) => `//   - ${line}`).join('\n')}
//
// ${adjusted.length} patterns are rewritten at load time:
${adjusted.map((line) => `//   - ${line}`).join('\n')}

import type { SecretRuleSource } from '#scan/rule'

export const SECRET_RULE_SOURCES: readonly SecretRuleSource[] = [
${kept.join('\n')}
]
`

await writeFile(new URL('../src/scan/secret-rules.ts', import.meta.url), file)
console.log(`wrote ${kept.length} rules, dropped ${skipped.length}, adjusted ${adjusted.length}`)
